# https://pub.dev/packages/yumemi_lints
include: package:yumemi_lints/flutter/3.19.0/recommended.yaml

analyzer:
  plugins:
    - custom_lint

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    use_setters_to_change_properties: false
