# https://pub.dev/packages/yumemi_lints
include: package:yumemi_lints/flutter/3.19.0/recommended.yaml

analyzer:
  plugins:
    - custom_lint

  errors:
    # freezedとjson_serializableを組み合わせて使用すると警告が出るため無視する設定を追加
    invalid_annotation_target: ignore

linter:
  rules:
    use_setters_to_change_properties: false
